### ISSUE TITLE
Operations difference

### ISSUE THREAD

**Issue by achilleas96** [tasosxak/nectar-lang#1]
what is the difference between y**=y*y and **y=y*y

**Comment by tasosxak** [comment]
if you have :

```swift
y:int = 5;
x:int;
x = y**;
say x,y;
```

```swift
y:int = 5;
x:int;
x = **y;
say x,y;
```
In the first snippet of code, you will get x =  5 and y =25 , while in the second case you will get  x=25 and y = 25.
